# Language flags
language: elixir

# OS matrix
os:
  - linux

# Matrix modifications.
jobs:
  include:
    - otp_release: 22.0
      elixir: 1.9
    - otp_release: 22.0
      elixir: 1.8
    - otp_release: 21.0
      elixir: 1.8
    - otp_release: 21.0
      elixir: 1.7
    - otp_release: 20.0
      elixir: 1.8
    - otp_release: 20.0
      elixir: 1.7
    - otp_release: 19.0
      elixir: 1.7

service:
    - redis-server

install:
  - mix local.rebar --force
  - mix local.hex --force

cache:
  directories:
    - _build

before_script:
  - mix deps.get

script:
  - epmd -daemon
  - mix test --trace
  - mix test --include cluster
